import { useEffect, useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Avatar, Badge, Button, Card, Col, Descriptions, Drawer, Dropdown, Empty, Input, Layout, Menu, Row, Select, Space, Statistic, Table, Tag, Typography, message } from 'antd';
import { BarChartOutlined, DashboardOutlined, DatabaseOutlined, FileSearchOutlined, HomeOutlined, LogoutOutlined, MedicineBoxOutlined, MenuFoldOutlined, MenuUnfoldOutlined, TeamOutlined, UserOutlined } from '@ant-design/icons';
import { api } from './api';
import type { AdminOverview, AdminUser, Analytics, AuditLog, Doctor, Hospital, Operation, Patient } from './types';
import './styles.css';
const { Header, Content, Sider } = Layout;

type Tab = 'dashboard'|'users'|'doctors'|'patients'|'operations'|'hospitals'|'analytics'|'audit';
const money = (v: string|number) => Number(v ?? 0).toLocaleString('en-US', { maximumFractionDigits: 2 });
const statusColor: Record<string,string> = { COMPLETED:'green', SCHEDULED:'blue', IN_PROGRESS:'orange', CANCELLED:'red', PAID:'green', UNPAID:'red', PARTIAL:'orange' };

function Login({ onLogin }: { onLogin:(token:string)=>void }) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const submit=async()=>{setLoading(true);setError('');try{const r=await api.post('/auth/login',{email,password});const token=r.data?.data?.token;const user=r.data?.data?.user;if(!token||user?.role!=='admin')throw new Error('This account does not have admin access.');localStorage.setItem('medaxis_admin_token',token);localStorage.setItem('medaxis_admin_user',JSON.stringify(user));onLogin(token);}catch(e){setError(e instanceof Error?e.message:'Login failed');}finally{setLoading(false)}};
  return <div className="login-shell"><Card className="login-card" bordered={false}><div className="login-mark">M</div><Typography.Title level={2}>MedAxis Admin</Typography.Title><Typography.Paragraph type="secondary">System administration and operational intelligence.</Typography.Paragraph><Input size="large" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} onPressEnter={submit}/><Input.Password size="large" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} onPressEnter={submit}/><Button type="primary" size="large" block loading={loading} onClick={submit}>Sign in</Button>{error&&<Alert className="login-error" message={error} type="error" showIcon/>}</Card></div>;
}

function StatCards({data}:{data:AdminOverview}) { return <Row gutter={[16,16]}>{[['Users',data.users,data.activeUsers],['Doctors',data.doctors,data.activeDoctors],['Patients',data.patients,null],['Operations',data.operations,null],['Hospitals',data.hospitals,data.activeHospitals]].map(([label,value,active])=><Col xs={24} sm={12} lg={Math.round(24/5)} key={String(label)}><Card className="stat-card"><Statistic title={String(label)} value={Number(value)} suffix={active!==null&&active!==undefined?<span className="stat-active">{active} active</span>:undefined}/></Card></Col>)}</Row>; }
function Dashboard({data}:{data:AdminOverview}) { return <Space direction="vertical" size={18} className="page-stack"><div><Typography.Title level={2}>System Overview</Typography.Title><Typography.Text type="secondary">Live platform health and activity across MedAxis.</Typography.Text></div><StatCards data={data}/><Row gutter={[16,16]}><Col xs={24} lg={10}><Card title="Revenue"><Row gutter={[12,12]}><Col span={8}><Statistic title="Total" value={money(data.revenue.totalCost)}/></Col><Col span={8}><Statistic title="Paid" value={money(data.revenue.totalPaid)}/></Col><Col span={8}><Statistic title="Remaining" value={money(data.revenue.totalRemaining)}/></Col></Row></Card></Col><Col xs={24} lg={14}><Card title="Operations by status"><div className="status-list">{data.operationStatus.map(x=><div className="status-row" key={x.status}><span><Tag color={statusColor[x.status]}>{x.status.replaceAll('_',' ')}</Tag></span><strong>{x.count}</strong></div>)}</div></Card></Col></Row><Card title="Recent operations"><Table rowKey="id" pagination={false} dataSource={data.recentOperations} columns={[{title:'Operation',dataIndex:'name'},{title:'Patient',render:(_:unknown,r:any)=>r.patient.fullName},{title:'Hospital',render:(_:unknown,r:any)=>r.hospital.name},{title:'Date',dataIndex:'operationDate',render:(v:string)=>new Date(v).toLocaleDateString()},{title:'Status',dataIndex:'status',render:(v:string)=><Tag color={statusColor[v]}>{v}</Tag>}]}/></Card></Space>; }

function ResourcePage<T extends object>({title,placeholder,queryKey,url,columns}:{title:string;placeholder:string;queryKey:string;url:string;columns:any[]}) { const [search,setSearch]=useState('');const [term,setTerm]=useState('');const q=useQuery({queryKey:[queryKey,term],queryFn:async()=>{const r=await api.get<{data:T[]}>(url,{params:term?{search:term}:undefined});return r.data.data;}});return <Space direction="vertical" size={18} className="page-stack"><div className="page-heading"><div><Typography.Title level={2}>{title}</Typography.Title><Typography.Text type="secondary">Manage and inspect platform records.</Typography.Text></div><Input.Search value={search} onChange={e=>setSearch(e.target.value)} onSearch={setTerm} placeholder={placeholder} allowClear/></div><Card>{q.isError?<Alert type="error" message={`Unable to load ${title.toLowerCase()}`}/>:<Table rowKey="id" loading={q.isLoading} dataSource={q.data} columns={columns} scroll={{x:900}} pagination={{pageSize:20,showSizeChanger:false}}/>}</Card></Space>; }

function UsersPage(){const qc=useQueryClient();return <ResourcePage<AdminUser> title="Users" placeholder="Search name or email" queryKey="users" url="/admin/users" columns={[{title:'User',render:(_:unknown,r:AdminUser)=><Space><Avatar src={r.avatarUrl} icon={<UserOutlined/>}/><div><strong>{r.name}</strong><div className="muted">{r.email}</div></div></Space>},{title:'Role',dataIndex:'role',render:(v:string,r:AdminUser)=><Select size="small" value={v} style={{width:120}} onChange={async role=>{await api.patch(`/admin/users/${r.id}`,{role});message.success('Role updated');qc.invalidateQueries({queryKey:['users']});}} options={['admin','doctor','user'].map(x=>({value:x,label:x}))}/>},{title:'Status',dataIndex:'isActive',render:(v:boolean,r:AdminUser)=><Button size="small" danger={v} onClick={async()=>{await api.patch(`/admin/users/${r.id}`,{isActive:!v});qc.invalidateQueries({queryKey:['users']});}}>{v?'Deactivate':'Activate'}</Button>},{title:'Verified',dataIndex:'emailVerifiedAt',render:(v:string|null)=><Badge status={v?'success':'default'} text={v?'Verified':'Pending'}/>}]}/>}
function DoctorsPage(){const qc=useQueryClient();return <ResourcePage<Doctor> title="Doctors" placeholder="Search doctor" queryKey="doctors" url="/admin/doctors" columns={[{title:'Doctor',dataIndex:'name',render:(v:string,r:Doctor)=><Space><Avatar icon={<MedicineBoxOutlined/>}/><div><strong>{v}</strong><div className="muted">{r.email||'No email'}</div></div></Space>},{title:'Specialties',render:(_:unknown,r:Doctor)=><Space wrap>{r.specialties?.slice(0,3).map((s:any)=><Tag key={s.specialty.name}>{s.specialty.name}</Tag>)}</Space>},{title:'Status',dataIndex:'isActive',render:(v:boolean,r:Doctor)=><Button size="small" danger={v} onClick={async()=>{await api.patch(`/admin/doctors/${r.id}`,{isActive:!v});qc.invalidateQueries({queryKey:['doctors']});}}>{v?'Deactivate':'Activate'}</Button>}]}/>}
function PatientsPage(){return <ResourcePage<Patient> title="Patients" placeholder="Search patient" queryKey="patients" url="/admin/patients" columns={[{title:'Patient',dataIndex:'fullName'},{title:'Age',dataIndex:'age'},{title:'Gender',dataIndex:'gender',render:(v:string)=><Tag>{v}</Tag>},{title:'Mobile',dataIndex:'mobile'},{title:'Operations',render:(_:unknown,r:Patient)=><strong>{r._count.operations}</strong>}]}/>}
function HospitalsPage(){const qc=useQueryClient();return <ResourcePage<Hospital> title="Hospitals" placeholder="Search hospital or city" queryKey="hospitals" url="/admin/hospitals" columns={[{title:'Hospital',dataIndex:'name'},{title:'Location',render:(_:unknown,r:Hospital)=>r.city||r.governorate?.nameEn||'—'},{title:'Operations',render:(_:unknown,r:Hospital)=>r._count.operations},{title:'Status',dataIndex:'isActive',render:(v:boolean,r:Hospital)=><Button size="small" danger={v} onClick={async()=>{await api.patch(`/admin/hospitals/${r.id}`,{isActive:!v});qc.invalidateQueries({queryKey:['hospitals']});}}>{v?'Deactivate':'Activate'}</Button>}]}/>}
function OperationsPage(){const [status,setStatus]=useState<string>();const q=useQuery({queryKey:['operations',status],queryFn:async()=>{const r=await api.get<{data:Operation[]}>('/admin/operations',{params:status?{status}:undefined});return r.data.data;}});return <Space direction="vertical" size={18} className="page-stack"><div className="page-heading"><div><Typography.Title level={2}>Operations</Typography.Title><Typography.Text type="secondary">System-wide surgical case visibility.</Typography.Text></div><Select allowClear placeholder="Filter status" value={status} onChange={setStatus} style={{width:180}} options={Object.keys(statusColor).filter(x=>['COMPLETED','SCHEDULED','IN_PROGRESS','CANCELLED'].includes(x)).map(x=>({value:x,label:x}))}/></div><Card><Table rowKey="id" loading={q.isLoading} dataSource={q.data} scroll={{x:1000}} pagination={{pageSize:20}} columns={[{title:'Operation',dataIndex:'name'},{title:'Patient',render:(_:unknown,r:Operation)=>r.patient.fullName},{title:'Hospital',render:(_:unknown,r:Operation)=>r.hospital.name},{title:'Specialty',render:(_:unknown,r:Operation)=>r.specialty?.name||'—'},{title:'Date',dataIndex:'operationDate',render:(v:string)=>new Date(v).toLocaleDateString()},{title:'Status',dataIndex:'status',render:(v:string)=><Tag color={statusColor[v]}>{v}</Tag>},{title:'Cost',render:(_:unknown,r:Operation)=>r.cost?money(r.cost.totalCost):'—'}]}/></Card></Space>}
function AnalyticsPage(){const q=useQuery({queryKey:['analytics'],queryFn:async()=>{const r=await api.get<{data:Analytics}>('/admin/analytics');return r.data.data;}});const max=Math.max(1,...(q.data?.monthly||[]).map(x=>x.count));return <Space direction="vertical" size={18} className="page-stack"><div><Typography.Title level={2}>Analytics</Typography.Title><Typography.Text type="secondary">Platform-wide operational trends.</Typography.Text></div>{q.data&&<><Row gutter={[16,16]}><Col xs={24} lg={14}><Card title="Operations by month"><div className="bar-chart">{q.data.monthly.slice(-12).map(x=><div className="bar-item" key={x.month}><div className="bar-track"><div className="bar-fill" style={{height:`${Math.max(6,x.count/max*100)}%`}}/></div><span>{x.month.slice(5)}</span><b>{x.count}</b></div>)}</div></Card></Col><Col xs={24} lg={10}><Card title="Top specialties"><RankList data={q.data.bySpecialty.slice(0,8)}/></Card></Col></Row><Row gutter={[16,16]}><Col xs={24} lg={14}><Card title="Top hospitals"><RankList data={q.data.byHospital.slice(0,8)}/></Card></Col><Col xs={24} lg={10}><Card title="Follow-ups"><RankList data={q.data.followUps.map(x=>({name:x.status,count:x._count.id}))}/><div className="metric-foot">Clinical files: <strong>{q.data.files}</strong></div></Card></Col></Row></>}</Space>}
function RankList({data}:{data:Array<{name:string;count:number}>}){return <div className="rank-list">{data.length?data.map((x,i)=><div className="rank-row" key={x.name}><span className="rank-no">{i+1}</span><span>{x.name}</span><strong>{x.count}</strong></div>):<Empty image={Empty.PRESENTED_IMAGE_SIMPLE}/>}</div>}
function AuditPage(){const q=useQuery({queryKey:['audit'],queryFn:async()=>{const r=await api.get<{data:AuditLog[]}>('/admin/audit-logs');return r.data.data;}});return <Space direction="vertical" size={18} className="page-stack"><div><Typography.Title level={2}>Audit Logs</Typography.Title><Typography.Text type="secondary">Timeline activity recorded by the clinical platform.</Typography.Text></div><Card><Table rowKey="id" loading={q.isLoading} dataSource={q.data} scroll={{x:1000}} pagination={{pageSize:25}} columns={[{title:'Time',dataIndex:'createdAt',render:(v:string)=>new Date(v).toLocaleString()},{title:'Action',dataIndex:'action',render:(v:string)=><Tag>{v.replaceAll('_',' ')}</Tag>},{title:'User',render:(_:unknown,r:AuditLog)=>r.user.name},{title:'Operation',render:(_:unknown,r:AuditLog)=>r.operation.name},{title:'Description',dataIndex:'description'}]}/></Card></Space>}

export default function App(){const [token,setToken]=useState(localStorage.getItem('medaxis_admin_token'));const [tab,setTab]=useState<Tab>('dashboard');const [collapsed,setCollapsed]=useState(false);const overview=useQuery({queryKey:['admin','overview'],queryFn:async()=>{const r=await api.get<{data:AdminOverview}>('/admin/overview');return r.data.data;},enabled:!!token});useEffect(()=>{if(!token) setTab('dashboard')},[token]);if(!token)return <Login onLogin={setToken}/>;const user=JSON.parse(localStorage.getItem('medaxis_admin_user')||'{}');const items=[['dashboard','Dashboard',<DashboardOutlined/>],['users','Users',<TeamOutlined/>],['doctors','Doctors',<MedicineBoxOutlined/>],['patients','Patients',<UserOutlined/>],['operations','Operations',<DatabaseOutlined/>],['hospitals','Hospitals',<HomeOutlined/>],['analytics','Analytics',<BarChartOutlined/>],['audit','Audit Logs',<FileSearchOutlined/>]] as const;const content=overview.isError?<Alert type="error" showIcon message="Unable to load system overview"/>:tab==='dashboard'&&overview.data?<Dashboard data={overview.data}/>:tab==='users'?<UsersPage/>:tab==='doctors'?<DoctorsPage/>:tab==='patients'?<PatientsPage/>:tab==='operations'?<OperationsPage/>:tab==='hospitals'?<HospitalsPage/>:tab==='analytics'?<AnalyticsPage/>:<AuditPage/>;return <Layout className="app-shell"><Sider collapsible collapsed={collapsed} trigger={null} theme="dark" width={250}><div className="brand"><span className="brand-logo">M</span>{!collapsed&&<><strong>MedAxis</strong><small>ADMIN</small></>}</div><Menu theme="dark" mode="inline" selectedKeys={[tab]} onClick={({key})=>setTab(key as Tab)} items={items.map(([key,label,icon])=>({key,label,icon}))}/></Sider><Layout><Header className="topbar"><Button type="text" icon={collapsed?<MenuUnfoldOutlined/>:<MenuFoldOutlined/>} onClick={()=>setCollapsed(!collapsed)}/><Space><Avatar src={user.avatarUrl} icon={<UserOutlined/>}/><div className="admin-user"><strong>{user.name||'Administrator'}</strong><span>Administrator</span></div><Dropdown menu={{items:[{key:'logout',label:'Sign out',icon:<LogoutOutlined/>} ],onClick:({key})=>{if(key==='logout'){localStorage.removeItem('medaxis_admin_token');localStorage.removeItem('medaxis_admin_user');setToken(null);}}}}><Button type="text">•••</Button></Dropdown></Space></Header><Content className="content">{content}</Content></Layout></Layout>}
